### ISSUE TITLE
nonlinear problem

### ISSUE THREAD

**Issue by vavrines** [timueh/PolyChaos.jl#24]
Hi timueh,

Do you have any advice or comments in the current framework if I want to evaluate nonlinear moments, e.g. < exp(\sum f_i \Phi_i), \Phi_k > ?

**Comment by timueh** [comment]
Hi @vavrines, in this case, intrusive PCE won't work, because you cannot project analytically onto the subspace. However, you can still solve the integral numerically via quadrature

<img src="http://latex.codecogs.com/gif.latex?\int \exp\left(\sum_{i} f_i(t) \phi_i(t)\right) \phi_k(t) \rho \mathrm{d} t \approx \sum_{j} w_j h(\tau_j)" border="0"/>

where 

<img src="http://latex.codecogs.com/gif.latex?h(\tau_j) = \exp\left(\sum_{i} f_i(\tau_j) \phi_i(\tau_j)\right) \phi_k(\tau_k) " border="0"/>

The quadrature rule you can construct via `PolyChaos.jl`.

Actually, that would make for a nice example! I know that for a gaussian random variable x, the PCE coefficients for exp(x) admit an analytical solution. That would allow to compare against quadrature.

**Comment by timueh** [comment]
Hi @vavrines, I added an [example.](https://github.com/timueh/PolyChaos.jl/blob/master/examples/NonintrusivePCE.ipynb) Hope it helps.
