### ISSUE TITLE
uniform distribution [-1,1]

### ISSUE THREAD

**Issue by vavrines** [timueh/PolyChaos.jl#30]
Hi @timueh,

I tried to se a new default OrthoPoly to denote uniform distribution [-1,1].
I met an issue as follows.

```
using PolyChaos

Type_for_domain = Tuple{Float64, Float64}
struct Uniform_11Measure <: AbstractCanonicalMeasure
    w::Function
    dom::Type_for_domain
    symmetric::Bool

    function Uniform_11Measure()
        new(x->0.5, (-1,1), true)
    end
end

struct Uniform_11OrthoPoly{V, M, Q} <: AbstractCanonicalOrthoPoly#{V, M, Q}
    deg::Int          # maximum degree
    α::V  # recurrence coefficients
    β::V  # recurrence coefficients
    measure::M
    quad::Q

    # inner constructor
    function Uniform_11OrthoPoly(deg::Int;Nrec::Int=deg+1, addQuadrature::Bool = true)
        #_checkConsistency(deg, Nrec)
        α, β = r_scale(1., rm_legendre(Nrec)...)
        quadrature = addQuadrature ?  Quad(length(α)-1,α,β) : EmptyQuad()
        new{promote_type(typeof(α), typeof(β)), Uniform_11Measure, typeof(quadrature)}(deg, α, β, Uniform_11Measure(), quadrature)
    end
end

a = Uniform_11OrthoPoly(5);
showpoly(0:5,a)

1
x
x^2 - 0.33
x^3 - 0.6x
x^4 - 0.86x^2 + 0.09
x^5 - 1.11x^3 + 0.24x
```

It's okay up to now. However, when I examined the recurrence coefficient, I found there might be something wrong. The variance
```
var([0,1],a)
0.6666666666666666
```
of a uniform distribution [-1,1] doesn't equal to its correct value 1/3.
I thins it's due to the coefficient,
```
a.β
2.0                
 0.3333333333333333 
 0.26666666666666666
 0.2571428571428571 
 0.25396825396825395
 0.25252525252525254
```
where the first element should be equal to 1.
Could we try to fix it?

**Comment by vavrines** [comment]
This way works.

```
using PolyChaos
supp = (-1,1)
uni_meas = Measure("uni_meas", x->0.5, supp, true)
b = OrthoPoly("uni_op", 5, uni_meas);

var([0,1],b)
0.3333333333333332
```

I might have misused the function rm_jacobi, not sure about it yet.

**Comment by timueh** [comment]
Hi there,

the problem with your first attempt is that you don't normalize the measure when computing the recurrence coefficients. That's what the function [`r_scale()`](https://timueh.github.io/PolyChaos.jl/stable/functions/#PolyChaos.r_scale) is for.

Instead of
```julia
α, β = r_scale(1., rm_legendre(Nrec)...)
```
write
```julia
α, β = r_scale(0.5, rm_legendre(Nrec)...)
```

Note: your first approach is definitely cleaner and numerically more stable because you compute the recurrence coefficients based on `rm_legendre()`. Put differently: you exploit the fact that we have a closed form of the recurrence coefficients.

The second approach is more intuitive from a coding-point-of-view, but does not exploit the fact that we have a closed form of the recurrence coefficients.

**Comment by vavrines** [comment]
Maybe I should spend some time catching up polynomials... : )
Anyway I finished the support for uniform distribution [-1,1], and created a pull request.
